mode: preprocessing    # train, test, inference, tryout, preprocessing

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  use_amp: False
  scaler: None
  checkpoint_dir: "./checkpoint_dir"
  criterion: "iou"
  optimizer: "not sure"
  checkpoint_best_model: True
  val_steps: 5
  lr_scheduler: None

test:
  metrices: []
  batch_size: 5

model:
  name: "sam2"
  check_point_path: None

data:
  name: "paris"  # paris, fipm
  path: "C:/Users/tippolito/Data/Benchmark"  # "C:/Users/tippolito/Data/Benchmark", "D:/Studium/Master/Repos/MCR-Lab/data/paris_lille_3d"

device: cpu  # cpu, cuda, cuda:0




