mode: tryout    # train, test, tryout, preprocessing

train:
  batch_size: 32
  epochs: 10

test:
  metrices: []

model:
  name: resnet

data:
  name: "paris"  # paris, fipm
  path: "D:/Studium/Master/Repos/MCR-Lab/data/paris_lille_3d"  # "C:/Users/tippolito/Data/Benchmark"

device: cpu  # cpu, cuda, cuda:0




